"""
JSONL Exporter for Gemini 3 Flash Supervised Fine-Tuning (SFT) - Milestone M2.3

This script extracts "Golden" solutions generated by Gemini 3.1 Pro (Teacher Model)
from both NCERT (`questiondata`) and JEE (`jee_question_bank`) tables.

It formats the input-output pairs into the OpenAI JSONL ChatML format (also supported 
by Vertex AI tuning jobs), consisting of `system`, `user`, and `model` roles.

Usage:
  python jsonl_exporter.py --output dataset.jsonl
"""

import sys
import os
import json
import logging
from pathlib import Path

cwd = Path(__file__).resolve().parent
if str(cwd) not in sys.path:
    sys.path.insert(0, str(cwd))

project_root = cwd.parent.parent
extraction_dir = project_root / "pipelines" / "ExtractionPipeline" / "SchoolDataExtraction" / "MultiStep"
jee_ascent_dir = project_root / "pipelines" / "JEEAscentPipeline"
sys.path.insert(0, str(extraction_dir))
sys.path.insert(0, str(jee_ascent_dir))

try:
    from db_writer import JEEExtractionDBWriter
except ImportError as e:
    print(f"Failed to import DB writer: {e}")
    sys.exit(1)

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
LOGGER = logging.getLogger(__name__)

def get_db_writer() -> JEEExtractionDBWriter:
    # Use the robust single-source DB connection wrapper
    return JEEExtractionDBWriter()

def extract_ncert_solutions(db_writer: JEEExtractionDBWriter) -> list:
    """Extract APPROVED_GOLD NCERT solutions from questiondata table."""
    LOGGER.info("Extracting NCERT golden solutions...")
    # Only export rows that have cleared the strict 5/5/5 GOLD gate.
    query = """
        SELECT q.questionid, q.content, q.solution
        FROM questiondata q
        WHERE q.solution IS NOT NULL
          AND q.review_status = 'APPROVED_GOLD';
    """
    results = []
    with db_writer.connection() as conn:
        with conn.cursor() as cur:
            cur.execute(query)
            for row in cur.fetchall():
                q_id, content, solution = row
                if content and solution:
                     results.append({
                         "source": "ncert",
                         "id": q_id,
                         "content": content,
                         "solution": solution
                     })
    LOGGER.info(f"Extracted {len(results)} NCERT solutions.")
    return results

def extract_jee_solutions(db_writer: JEEExtractionDBWriter) -> list:
    """Extract newly generated JEE solutions from jee_question_bank table."""
    LOGGER.info("Extracting JEE golden solutions...")
    query = """
        SELECT id, subject, question_content, solution 
        FROM jee_question_bank
        WHERE solution IS NOT NULL 
          AND review_status = 'APPROVED_GOLD'
        LIMIT 500;
    """
    results = []
    with db_writer.connection() as conn:
        with conn.cursor() as cur:
            cur.execute(query)
            for row in cur.fetchall():
                q_id, subject, qc, solution = row
                if qc and solution:
                     results.append({
                         "source": "jee",
                         "id": q_id,
                         "subject": subject,
                         "content": qc,
                         "solution": solution
                     })
    LOGGER.info(f"Extracted {len(results)} JEE solutions.")
    return results

def format_system_prompt(subject: str = "Maths/Physics/Chemistry") -> str:
    return (
        "You are an expert IIT-JEE Tutor. Your goal is to solve the provided problem step-by-step. "
        "Output ONLY the final solution perfectly structured as a JSON object matching the universal schema. "
        "Do not guess missing information or hallucinate diagram elements."
    )

def format_chatml(system_text: str, user_content, model_content: dict) -> dict:
    """Format single payload into ChatML/Vertex structure.

    `user_content` may be either:
      - a string (text-only training mode, the default)
      - a list of parts: [{"type": "text", "text": "..."}, {"type": "image_url", "image_url": {"url": "..."}}]
        (multimodal mode — convert_to_vertex_jsonl.py downstream fetches image bytes
        and emits Vertex inlineData parts).
    """
    return {
        "messages": [
            {"role": "system", "content": system_text},
            {"role": "user", "content": user_content},
            {"role": "model", "content": json.dumps(model_content)}
        ]
    }


def extract_image_urls_for_source(source: str, content) -> list:
    """Return list of image URLs to include in multimodal training.

    NCERT: pulls from `content.figure_info[*].url` (mirrors
    build_holdout_set._extract_ncert_image_urls).
    JEE: returns [] in practice — `figure_url` is NULL on 100% of jee_question_bank
    (KI-3). Even if we look at the field, we won't find URLs.
    """
    if isinstance(content, str):
        try:
            content = json.loads(content)
        except Exception:
            return []
    if not isinstance(content, dict):
        return []
    urls = []
    if source == "ncert":
        fi = content.get("figure_info") or []
        if isinstance(fi, list):
            for entry in fi:
                if isinstance(entry, dict):
                    u = entry.get("url")
                    if u:
                        urls.append(u)
    else:  # jee
        if content.get("figure_url"):
            urls.append(content["figure_url"])
        opt_urls = content.get("option_figure_urls") or []
        if isinstance(opt_urls, list):
            urls.extend(u for u in opt_urls if u)
    return urls


def build_user_payload(content) -> str:
    """Normalized inference-time problem payload, consistent across NCERT and JEE.

    The answer key is deliberately EXCLUDED — the SFT `user` message must mirror what
    the model sees at serving time (an unseen problem, no answer). Image attachments
    in multimodal mode are added separately by build_user_content_multimodal.
    """
    if isinstance(content, str):
        try:
            content = json.loads(content)
        except Exception:
            content = {}
    if not isinstance(content, dict):
        content = {}
    payload = {
        "problem_text": (content.get("problem_text") or content.get("raw_text")
                         or content.get("question_text") or content.get("text") or ""),
        "options": content.get("options", []),
    }
    return json.dumps(payload, indent=2)


def build_user_content_multimodal(text_payload: str, image_urls: list) -> list:
    """Compose ChatML user content as a list-of-parts (text + image_urls).

    Used in --multimodal mode. The text payload is a single text part; each image URL
    becomes an `image_url` part. convert_to_vertex_jsonl.py downstream fetches the
    image bytes (via gemini_client._fetch_image_bytes) and emits Vertex inlineData.
    """
    parts = [{"type": "text", "text": text_payload}]
    for url in image_urls:
        parts.append({"type": "image_url", "image_url": {"url": url}})
    return parts


import argparse

def _render_user_content(text_payload: str, source: str, content, multimodal: bool):
    """Return user-message content. String in text-only mode; list-of-parts in multimodal."""
    prefixed = "Solve this problem:\n\n" + text_payload
    if not multimodal:
        return prefixed
    image_urls = extract_image_urls_for_source(source, content)
    if not image_urls:
        return prefixed  # row has no figure -> text-only part anyway
    return build_user_content_multimodal(prefixed, image_urls)


def main():
    parser = argparse.ArgumentParser(description="Export JSONL dataset for SFT")
    parser.add_argument("--source", type=str, choices=["all", "jee", "ncert"], default="all", help="Which data source to extract")
    parser.add_argument("--output", type=str, default="m2_sft_dataset.jsonl", help="Output file name")
    parser.add_argument(
        "--multimodal", action="store_true",
        help="Emit image_url parts in user content when a row has figure_info[*].url (NCERT) "
             "or figure_url (JEE, KI-3-blocked). convert_to_vertex_jsonl.py --multimodal "
             "downstream fetches the bytes and emits Vertex inlineData parts.",
    )
    args = parser.parse_args()

    db_writer = get_db_writer()

    output_lines = []
    image_lines = 0

    # Process NCERT
    if args.source in ["all", "ncert"]:
        all_ncert = extract_ncert_solutions(db_writer)
        for item in all_ncert:
            sys_prompt = format_system_prompt()
            user_payload = build_user_payload(item["content"])
            user_content = _render_user_content(user_payload, "ncert", item["content"], args.multimodal)
            if isinstance(user_content, list):
                image_lines += 1
            line = format_chatml(sys_prompt, user_content, item["solution"])
            output_lines.append(line)

    # Process JEE
    if args.source in ["all", "jee"]:
        all_jee = extract_jee_solutions(db_writer)
        for item in all_jee:
            sys_prompt = format_system_prompt(item["subject"])
            user_payload = build_user_payload(item["content"])
            user_content = _render_user_content(user_payload, "jee", item["content"], args.multimodal)
            if isinstance(user_content, list):
                image_lines += 1
            line = format_chatml(sys_prompt, user_content, item["solution"])
            output_lines.append(line)

    output_path = Path(args.output)
    with open(output_path, "w", encoding="utf-8") as f:
         for line in output_lines:
              f.write(json.dumps(line) + "\n")

    LOGGER.info(f"Successfully wrote {len(output_lines)} examples to {output_path} "
                f"(multimodal={args.multimodal}, lines with image parts={image_lines})")

if __name__ == "__main__":
    main()
